[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[context.production.environment]
  GEMINI_API_KEY = "your_gemini_api_key_here"