[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[context.production.environment]
  GEMINI_API_KEY = "AIzaSyDY_VvRnxpgdVRBAgJIbOtphouOa6PogHc"
  ASTROLOGY_API_AUTH = "639992:cfd7ec38dd5a3876b58a0e6d1d4c340e6a71141c"